 
 
  en:
    languageCode: en-us
    contentDir: content/
    languageName: English
    baseURL: "https://www.ims.tsukuba.ac.jp/~sma_lab/"
    weight: 1

  ja:
    languageCode: ja
    contentDir: content/ja/
    languageName: 日本語
    weight: 2
    baseURL: "https://www.ims.tsukuba.ac.jp/~sma_lab/"

